import { Week } from "./types/Week";

export const steps: Week[] = [
  {
    weekNum: 1,
    title: "Power Building",
    desc: "In this week we are going to focus on both power and volume. We will start each workout with functional exercises and continue working on isolated exercises with greater volume",
    workouts: [
      {
        id: 0,
        isComplete: true,
        isGolden: true,
        type: "Health",
        icon: "randomAssIcon",
        exercises: [
          {
            isDone: true,
            muscleGroup: "Arms",
            numOfRepsPerSet: 10,
            numOfSets: 3,
            repsPerSetLitrely: [0, 0, 0, 0],
            restTimePerSet: 60,
            type: "intermadiant",
            exerciseName: "Biceps curl",
            exerciseDiscription:
              "the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise",
          },
          {
            isDone: true,
            muscleGroup: "Arms",
            numOfRepsPerSet: 10,
            numOfSets: 3,
            repsPerSetLitrely: [],
            restTimePerSet: 60,
            type: "intermadiant",
            exerciseName: "Overhead tricep extension",
            exerciseDiscription:
              "the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise",
          },
          {
            isDone: true,
            muscleGroup: "Arms",
            numOfRepsPerSet: 10,
            numOfSets: 3,
            repsPerSetLitrely: [],
            restTimePerSet: 60,
            type: "intermadiant",
            exerciseName: "Hammer curl",
            exerciseDiscription:
              "the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise",
          },
          {
            isDone: true,
            muscleGroup: "Arms",
            numOfRepsPerSet: 10,
            numOfSets: 3,
            repsPerSetLitrely: [],
            restTimePerSet: 60,
            type: "intermadiant",
            exerciseName: "exercise name",
            exerciseDiscription:
              "the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise",
          },
        ],

        workoutName: "name of workout",
      },
      {
        id: 1,
        isComplete: true,
        isGolden: false,
        type: "Health",
        icon: "randomAssIcon",
        exercises: [
          {
            isDone: true,
            muscleGroup: "Arms",
            numOfRepsPerSet: 10,
            numOfSets: 3,
            repsPerSetLitrely: [],
            restTimePerSet: 60,
            type: "intermadiant",
            exerciseName: "exercise name",
            exerciseDiscription:
              "the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise",
          },
        ],
        workoutName: "name of workout",
      },
      {
        id: 2,
        isComplete: true,
        isGolden: true,
        type: "Health",
        icon: "randomAssIcon",
        exercises: [
          {
            isDone: true,
            muscleGroup: "Arms",
            numOfRepsPerSet: 10,
            numOfSets: 3,
            repsPerSetLitrely: [],
            restTimePerSet: 60,
            type: "intermadiant",
            exerciseName: "exercise name",
            exerciseDiscription:
              "the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise",
          },
        ],
        workoutName: "name of workout",
      },
      {
        id: 3,
        isComplete: false,
        isGolden: false,
        type: "Health",
        icon: "randomAssIcon",
        exercises: [
          {
            isDone: true,
            muscleGroup: "Arms",
            numOfRepsPerSet: 10,
            numOfSets: 3,
            repsPerSetLitrely: [],
            restTimePerSet: 60,
            type: "intermadiant",
            exerciseName: "exercise name",
            exerciseDiscription:
              "the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise",
          },
        ],
        workoutName: "name of workout",
      },
      {
        id: 4,
        isComplete: true,
        isGolden: true,
        type: "Health",
        icon: "randomAssIcon",
        exercises: [
          {
            isDone: true,
            muscleGroup: "Arms",
            numOfRepsPerSet: 10,
            numOfSets: 3,
            repsPerSetLitrely: [],
            restTimePerSet: 60,
            type: "intermadiant",
            exerciseName: "exercise name",
            exerciseDiscription:
              "the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise",
          },
        ],
        workoutName: "name of workout",
      },
      {
        id: 5,
        isComplete: true,
        isGolden: true,
        type: "Health",
        icon: "randomAssIcon",
        exercises: [
          {
            isDone: true,
            muscleGroup: "Arms",
            numOfRepsPerSet: 10,
            numOfSets: 3,
            repsPerSetLitrely: [],
            restTimePerSet: 60,
            type: "intermadiant",
            exerciseName: "exercise name",
            exerciseDiscription:
              "the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise",
          },
        ],
        workoutName: "name of workout",
      },
      {
        id: 6,
        isComplete: true,
        isGolden: true,
        type: "Health",
        icon: "randomAssIcon",
        exercises: [
          {
            isDone: true,
            muscleGroup: "Arms",
            numOfRepsPerSet: 10,
            numOfSets: 3,
            repsPerSetLitrely: [],
            restTimePerSet: 60,
            type: "intermadiant",
            exerciseName: "exercise name",
            exerciseDiscription:
              "the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise",
          },
        ],
        workoutName: "name of workout",
      },
    ],
  },
  {
    weekNum: 2,
    title: "Power Building",
    desc: "In this week we are going to focus on both power and volume. We will start each workout with functional exercises and continue working on isolated exercises with greater volume",
    workouts: [
      {
        id: 0,
        isComplete: true,
        isGolden: true,
        type: "Health",
        icon: "randomAssIcon",
        exercises: [
          {
            isDone: true,
            muscleGroup: "Arms",
            numOfRepsPerSet: 10,
            numOfSets: 3,
            repsPerSetLitrely: [],
            restTimePerSet: 60,
            type: "intermadiant",
            exerciseName: "exercise name",
            exerciseDiscription:
              "the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise",
          },
        ],
        workoutName: "name of workout",
      },
      {
        id: 0,
        isComplete: true,
        isGolden: false,
        type: "Health",
        icon: "randomAssIcon",
        exercises: [
          {
            isDone: true,
            muscleGroup: "Arms",
            numOfRepsPerSet: 10,
            numOfSets: 3,
            repsPerSetLitrely: [],
            restTimePerSet: 60,
            type: "intermadiant",
            exerciseName: "exercise name",
            exerciseDiscription:
              "the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise",
          },
        ],
        workoutName: "name of workout",
      },
      {
        id: 0,
        isComplete: true,
        isGolden: true,
        type: "Health",
        icon: "randomAssIcon",
        exercises: [
          {
            isDone: true,
            muscleGroup: "Arms",
            numOfRepsPerSet: 10,
            numOfSets: 3,
            repsPerSetLitrely: [],
            restTimePerSet: 60,
            type: "intermadiant",
            exerciseName: "exercise name",
            exerciseDiscription:
              "the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise",
          },
        ],
        workoutName: "name of workout",
      },
      {
        id: 0,
        isComplete: true,
        isGolden: true,
        type: "Health",
        icon: "randomAssIcon",
        exercises: [
          {
            isDone: true,
            muscleGroup: "Arms",
            numOfRepsPerSet: 10,
            numOfSets: 3,
            repsPerSetLitrely: [],
            restTimePerSet: 60,
            type: "intermadiant",
            exerciseName: "exercise name",
            exerciseDiscription:
              "the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise",
          },
        ],
        workoutName: "name of workout",
      },
      {
        id: 0,
        isComplete: true,
        isGolden: true,
        type: "Health",
        icon: "randomAssIcon",
        exercises: [
          {
            isDone: true,
            muscleGroup: "Arms",
            numOfRepsPerSet: 10,
            numOfSets: 3,
            repsPerSetLitrely: [],
            restTimePerSet: 60,
            type: "intermadiant",
            exerciseName: "exercise name",
            exerciseDiscription:
              "the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise",
          },
        ],
        workoutName: "name of workout",
      },
      {
        id: 0,
        isComplete: true,
        isGolden: true,
        type: "Health",
        icon: "randomAssIcon",
        exercises: [
          {
            isDone: true,
            muscleGroup: "Arms",
            numOfRepsPerSet: 10,
            numOfSets: 3,
            repsPerSetLitrely: [],
            restTimePerSet: 60,
            type: "intermadiant",
            exerciseName: "exercise name",
            exerciseDiscription:
              "the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise",
          },
        ],
        workoutName: "name of workout",
      },
      {
        id: 0,
        isComplete: true,
        isGolden: true,
        type: "Health",
        icon: "randomAssIcon",
        exercises: [
          {
            isDone: true,
            muscleGroup: "Arms",
            numOfRepsPerSet: 10,
            numOfSets: 3,
            repsPerSetLitrely: [],
            restTimePerSet: 60,
            type: "intermadiant",
            exerciseName: "exercise name",
            exerciseDiscription:
              "the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise",
          },
        ],
        workoutName: "name of workout",
      },
    ],
  },
  {
    weekNum: 3,
    title: "Power Building",
    desc: "In this week we are going to focus on both power and volume. We will start each workout with functional exercises and continue working on isolated exercises with greater volume",
    workouts: [
      {
        id: 0,
        isComplete: true,
        isGolden: true,
        type: "Health",
        icon: "randomAssIcon",
        exercises: [
          {
            isDone: true,
            muscleGroup: "Arms",
            numOfRepsPerSet: 10,
            numOfSets: 3,
            repsPerSetLitrely: [],
            restTimePerSet: 60,
            type: "intermadiant",
            exerciseName: "exercise name",
            exerciseDiscription:
              "the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise",
          },
        ],
        workoutName: "name of workout",
      },
      {
        id: 0,
        isComplete: true,
        isGolden: true,
        type: "Health",
        icon: "randomAssIcon",
        exercises: [
          {
            isDone: true,
            muscleGroup: "Arms",
            numOfRepsPerSet: 10,
            numOfSets: 3,
            repsPerSetLitrely: [],
            restTimePerSet: 60,
            type: "intermadiant",
            exerciseName: "exercise name",
            exerciseDiscription:
              "the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise",
          },
        ],
        workoutName: "name of workout",
      },
      {
        id: 0,
        isComplete: true,
        isGolden: true,
        type: "Health",
        icon: "randomAssIcon",
        exercises: [
          {
            isDone: true,
            muscleGroup: "Arms",
            numOfRepsPerSet: 10,
            numOfSets: 3,
            repsPerSetLitrely: [],
            restTimePerSet: 60,
            type: "intermadiant",
            exerciseName: "exercise name",
            exerciseDiscription:
              "the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise",
          },
        ],
        workoutName: "name of workout",
      },
      {
        id: 0,
        isComplete: true,
        isGolden: true,
        type: "Health",
        icon: "randomAssIcon",
        exercises: [
          {
            isDone: true,
            muscleGroup: "Arms",
            numOfRepsPerSet: 10,
            numOfSets: 3,
            repsPerSetLitrely: [],
            restTimePerSet: 60,
            type: "intermadiant",
            exerciseName: "exercise name",
            exerciseDiscription:
              "the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise",
          },
        ],
        workoutName: "name of workout",
      },
      {
        id: 0,
        isComplete: true,
        isGolden: true,
        type: "Health",
        icon: "randomAssIcon",
        exercises: [
          {
            isDone: true,
            muscleGroup: "Arms",
            numOfRepsPerSet: 10,
            numOfSets: 3,
            repsPerSetLitrely: [],
            restTimePerSet: 60,
            type: "intermadiant",
            exerciseName: "exercise name",
            exerciseDiscription:
              "the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise",
          },
        ],
        workoutName: "name of workout",
      },
      {
        id: 0,
        isComplete: true,
        isGolden: true,
        type: "Health",
        icon: "randomAssIcon",
        exercises: [
          {
            isDone: true,
            muscleGroup: "Arms",
            numOfRepsPerSet: 10,
            numOfSets: 3,
            repsPerSetLitrely: [],
            restTimePerSet: 60,
            type: "intermadiant",
            exerciseName: "exercise name",
            exerciseDiscription:
              "the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise",
          },
        ],
        workoutName: "name of workout",
      },
      {
        id: 0,
        isComplete: true,
        isGolden: true,
        type: "Health",
        icon: "randomAssIcon",
        exercises: [
          {
            isDone: true,
            muscleGroup: "Arms",
            numOfRepsPerSet: 10,
            numOfSets: 3,
            repsPerSetLitrely: [],
            restTimePerSet: 60,
            type: "intermadiant",
            exerciseName: "exercise name",
            exerciseDiscription:
              "the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise the discription of the exercise",
          },
        ],
        workoutName: "name of workout",
      },
    ],
  },
];
